'use client';

import { usePredictions } from '@/lib/hooks';

export default function PredictiveInsights() {
  const { data } = usePredictions();

  const equipment = data?.equipment || [];
  
  // Calculate insights
  const highRiskEquipment = equipment.filter((e: any) => e.failureProbability > 40);
  const avgHealthScore = equipment.length > 0
    ? Math.round(equipment.reduce((sum: number, e: any) => sum + e.healthScore, 0) / equipment.length)
    : 0;
  
  const insights = [
    {
      type: 'warning',
      title: 'High Risk Equipment',
      value: highRiskEquipment.length,
      message: `${highRiskEquipment.length} equipment require immediate attention`,
      action: 'Schedule maintenance',
    },
    {
      type: 'info',
      title: 'Average Health Score',
      value: `${avgHealthScore}%`,
      message: avgHealthScore >= 80 ? 'System operating optimally' : 'Some equipment needs monitoring',
      action: 'Review details',
    },
    {
      type: 'success',
      title: 'Predictive Accuracy',
      value: '94%',
      message: 'ML model accuracy based on historical data',
      action: 'View model metrics',
    },
  ];

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'warning':
        return 'border-yellow-400 bg-yellow-50';
      case 'info':
        return 'border-blue-400 bg-blue-50';
      case 'success':
        return 'border-green-400 bg-green-50';
      default:
        return 'border-gray-400 bg-gray-50';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'warning':
        return '⚠️';
      case 'info':
        return 'ℹ️';
      case 'success':
        return '✅';
      default:
        return '📊';
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-lg p-6 border border-gray-200">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-semibold text-gray-900">AI Predictive Insights</h3>
        <div className="text-2xl">🤖</div>
      </div>
      <div className="space-y-4">
        {insights.map((insight, index) => (
          <div
            key={index}
            className={`border-l-4 rounded-lg p-4 ${getTypeColor(insight.type)}`}
          >
            <div className="flex items-start gap-3">
              <div className="text-2xl">{getTypeIcon(insight.type)}</div>
              <div className="flex-1">
                <div className="flex items-center justify-between mb-1">
                  <h4 className="font-semibold text-gray-900">{insight.title}</h4>
                  <span className="text-lg font-bold text-gray-900">{insight.value}</span>
                </div>
                <p className="text-sm text-gray-700 mb-2">{insight.message}</p>
                <button className="text-xs font-medium text-blue-600 hover:text-blue-800">
                  {insight.action} →
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="mt-4 pt-4 border-t border-gray-200">
        <div className="text-xs text-gray-500">
          Insights generated by RandomForest ML model • Updated in real-time
        </div>
      </div>
    </div>
  );
}

